const mongoose = require('mongoose');
const { sequelize } = require('../config/database');
const Product = require('../models/Product');
const User = require('../models/User');
const dotenv = require('dotenv');

dotenv.config();

const sampleProducts = [
  // Electronics - 15 products
  {
    name: 'Apple MacBook Pro 16"',
    description: 'Powerful laptop with M2 Pro chip, 16GB RAM, 512GB SSD. Perfect for developers and creators.',
    price: 2499.99,
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Apple',
    images: [{ url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8', alt: 'MacBook Pro' }],
    stock: 25,
    ratings: { average: 4.8, count: 342 },
    isFeatured: true,
    discount: 10,
    specifications: { 'Processor': 'M2 Pro', 'RAM': '16GB', 'Storage': '512GB SSD', 'Display': '16-inch Retina' }
  },
  {
    name: 'Dell XPS 13 Laptop',
    description: 'Ultra-thin laptop with Intel Core i7, 16GB RAM, stunning InfinityEdge display.',
    price: 1299.99,
    category: 'Electronics',
    subcategory: 'Laptops',
    brand: 'Dell',
    images: [{ url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45', alt: 'Dell Laptop' }],
    stock: 40,
    ratings: { average: 4.6, count: 523 },
    specifications: { 'Processor': 'Intel Core i7', 'RAM': '16GB', 'Storage': '512GB SSD' }
  },
  {
    name: 'Sony WH-1000XM5 Wireless Headphones',
    description: 'Industry-leading noise canceling headphones with superior sound quality.',
    price: 399.99,
    category: 'Electronics',
    subcategory: 'Audio',
    brand: 'Sony',
    images: [{ url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e', alt: 'Headphones' }],
    stock: 150,
    ratings: { average: 4.7, count: 1205 },
    isFeatured: true,
    discount: 15,
  },
  {
    name: 'Samsung Galaxy S23 Ultra',
    description: '256GB storage, 12GB RAM, 200MP camera, 5G enabled smartphone.',
    price: 1199.99,
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Samsung',
    images: [{ url: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c', alt: 'Samsung Phone' }],
    stock: 80,
    ratings: { average: 4.6, count: 892 },
    isFeatured: true,
    discount: 5,
  },
  {
    name: 'Apple iPhone 15 Pro',
    description: '128GB, Titanium design, A17 Pro chip, ProMotion display.',
    price: 999.99,
    category: 'Electronics',
    subcategory: 'Smartphones',
    brand: 'Apple',
    images: [{ url: 'https://images.unsplash.com/photo-1592286927505-bf92d377fd2c', alt: 'iPhone' }],
    stock: 100,
    ratings: { average: 4.9, count: 1543 },
    isFeatured: true,
  },
  {
    name: 'LG 55" 4K OLED TV',
    description: 'Stunning picture quality with self-lit OLED pixels and Dolby Vision.',
    price: 1499.99,
    category: 'Electronics',
    subcategory: 'TVs',
    brand: 'LG',
    images: [{ url: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1', alt: 'OLED TV' }],
    stock: 30,
    ratings: { average: 4.8, count: 678 },
  },
  {
    name: 'Canon EOS R6 Camera',
    description: 'Full-frame mirrorless camera with 20MP sensor and 4K video.',
    price: 2499.00,
    category: 'Electronics',
    subcategory: 'Cameras',
    brand: 'Canon',
    images: [{ url: 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f', alt: 'Camera' }],
    stock: 20,
    ratings: { average: 4.9, count: 234 },
  },
  {
    name: 'Apple iPad Pro 12.9"',
    description: 'M2 chip, Liquid Retina XDR display, 256GB storage.',
    price: 1099.99,
    category: 'Electronics',
    subcategory: 'Tablets',
    brand: 'Apple',
    images: [{ url: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0', alt: 'iPad Pro' }],
    stock: 60,
    ratings: { average: 4.7, count: 890 },
  },
  {
    name: 'Amazon Echo Dot (5th Gen)',
    description: 'Smart speaker with Alexa, improved sound, and temperature sensor.',
    price: 49.99,
    category: 'Electronics',
    subcategory: 'Smart Home',
    brand: 'Amazon',
    images: [{ url: 'https://images.unsplash.com/photo-1543512214-318c7553f230', alt: 'Echo Dot' }],
    stock: 500,
    ratings: { average: 4.5, count: 3421 },
    discount: 40,
  },
  {
    name: 'Logitech MX Master 3S Mouse',
    description: 'Advanced wireless mouse with ultra-fast scrolling and ergonomic design.',
    price: 99.99,
    category: 'Electronics',
    subcategory: 'Accessories',
    brand: 'Logitech',
    images: [{ url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46', alt: 'Mouse' }],
    stock: 200,
    ratings: { average: 4.8, count: 1234 },
  },

  // Clothing - 15 products
  {
    name: 'Nike Air Max 270',
    description: 'Comfortable running shoes with Air Max cushioning technology.',
    price: 149.99,
    category: 'Clothing',
    subcategory: 'Shoes',
    brand: 'Nike',
    images: [{ url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff', alt: 'Nike Shoes' }],
    stock: 200,
    ratings: { average: 4.5, count: 567 },
    discount: 20,
  },
  {
    name: 'Adidas Ultraboost 22',
    description: 'Premium running shoes with responsive BOOST cushioning.',
    price: 189.99,
    category: 'Clothing',
    subcategory: 'Shoes',
    brand: 'Adidas',
    images: [{ url: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5', alt: 'Adidas Shoes' }],
    stock: 150,
    ratings: { average: 4.6, count: 432 },
  },
  {
    name: "Levi's 501 Original Fit Jeans",
    description: 'Classic straight fit jeans with button fly, iconic style.',
    price: 69.99,
    category: 'Clothing',
    subcategory: 'Pants',
    brand: "Levi's",
    images: [{ url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Jeans' }],
    stock: 300,
    ratings: { average: 4.7, count: 1234 },
  },
  {
    name: 'Columbia Fleece Jacket',
    description: 'Warm and comfortable fleece jacket for outdoor activities.',
    price: 79.99,
    category: 'Clothing',
    subcategory: 'Outerwear',
    brand: 'Columbia',
    images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea', alt: 'Jacket' }],
    stock: 120,
    ratings: { average: 4.4, count: 345 },
  },
  {
    name: 'Under Armour Performance T-Shirt',
    description: 'Moisture-wicking athletic shirt for training and sports.',
    price: 29.99,
    category: 'Clothing',
    subcategory: 'Activewear',
    brand: 'Under Armour',
    images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab', alt: 'T-Shirt' }],
    stock: 400,
    ratings: { average: 4.3, count: 678 },
  },
  {
    name: 'Calvin Klein Cotton Boxer Briefs 3-Pack',
    description: 'Comfortable cotton blend boxer briefs with elastic waistband.',
    price: 42.50,
    category: 'Clothing',
    subcategory: 'Underwear',
    brand: 'Calvin Klein',
    images: [{ url: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f', alt: 'Underwear' }],
    stock: 250,
    ratings: { average: 4.5, count: 892 },
  },
  {
    name: 'The North Face Puffer Jacket',
    description: 'Insulated winter jacket with water-resistant finish.',
    price: 249.99,
    category: 'Clothing',
    subcategory: 'Outerwear',
    brand: 'The North Face',
    images: [{ url: 'https://images.unsplash.com/photo-1539533018447-63fcce2678e3', alt: 'Puffer Jacket' }],
    stock: 90,
    ratings: { average: 4.8, count: 456 },
    discount: 15,
  },
  {
    name: 'Puma Track Pants',
    description: 'Comfortable athletic pants with side stripe design.',
    price: 54.99,
    category: 'Clothing',
    subcategory: 'Activewear',
    brand: 'Puma',
    images: [{ url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7', alt: 'Track Pants' }],
    stock: 180,
    ratings: { average: 4.2, count: 234 },
  },
  {
    name: 'Ralph Lauren Polo Shirt',
    description: 'Classic fit polo shirt with signature pony logo.',
    price: 89.50,
    category: 'Clothing',
    subcategory: 'Tops',
    brand: 'Ralph Lauren',
    images: [{ url: 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d', alt: 'Polo Shirt' }],
    stock: 220,
    ratings: { average: 4.6, count: 678 },
  },
  {
    name: "Women's Yoga Leggings",
    description: 'High-waisted, moisture-wicking leggings perfect for yoga and workouts.',
    price: 44.99,
    category: 'Clothing',
    subcategory: 'Activewear',
    brand: 'Lululemon',
    images: [{ url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8', alt: 'Leggings' }],
    stock: 300,
    ratings: { average: 4.7, count: 1432 },
  },
  {
    name: 'Timberland Boots',
    description: 'Classic waterproof leather boots with padded collar.',
    price: 189.99,
    category: 'Clothing',
    subcategory: 'Shoes',
    brand: 'Timberland',
    images: [{ url: 'https://images.unsplash.com/photo-1605812860427-4024433a70fd', alt: 'Boots' }],
    stock: 100,
    ratings: { average: 4.8, count: 567 },
  },
  {
    name: 'Champion Hoodie',
    description: 'Soft fleece hoodie with kangaroo pocket and ribbed cuffs.',
    price: 39.99,
    category: 'Clothing',
    subcategory: 'Tops',
    brand: 'Champion',
    images: [{ url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7', alt: 'Hoodie' }],
    stock: 350,
    ratings: { average: 4.4, count: 789 },
    discount: 10,
  },
  {
    name: 'Tommy Hilfiger Dress Shirt',
    description: 'Classic fit dress shirt with button-down collar.',
    price: 69.50,
    category: 'Clothing',
    subcategory: 'Formal',
    brand: 'Tommy Hilfiger',
    images: [{ url: 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf', alt: 'Dress Shirt' }],
    stock: 160,
    ratings: { average: 4.5, count: 345 },
  },
  {
    name: 'Converse Chuck Taylor All Star',
    description: 'Iconic canvas sneakers with rubber sole, available in multiple colors.',
    price: 65.00,
    category: 'Clothing',
    subcategory: 'Shoes',
    brand: 'Converse',
    images: [{ url: 'https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f', alt: 'Converse Shoes' }],
    stock: 400,
    ratings: { average: 4.6, count: 2134 },
  },
  {
    name: 'Patagonia Fleece Vest',
    description: 'Lightweight fleece vest for layering in cool weather.',
    price: 99.00,
    category: 'Clothing',
    subcategory: 'Outerwear',
    brand: 'Patagonia',
    images: [{ url: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633', alt: 'Fleece Vest' }],
    stock: 130,
    ratings: { average: 4.7, count: 423 },
  },

  // Books - 12 products
  {
    name: 'The Psychology of Money',
    description: 'Timeless lessons on wealth, greed, and happiness by Morgan Housel.',
    price: 16.99,
    category: 'Books',
    subcategory: 'Finance',
    brand: 'Harriman House',
    images: [{ url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f', alt: 'Book' }],
    stock: 500,
    ratings: { average: 4.9, count: 2134 },
    isFeatured: true,
  },
  {
    name: 'Atomic Habits',
    description: 'An Easy & Proven Way to Build Good Habits & Break Bad Ones by James Clear.',
    price: 14.99,
    category: 'Books',
    subcategory: 'Self-Help',
    brand: 'Penguin Random House',
    images: [{ url: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73', alt: 'Book' }],
    stock: 400,
    ratings: { average: 4.8, count: 5678 },
    isFeatured: true,
  },
  {
    name: 'Project Hail Mary',
    description: 'Sci-fi thriller by Andy Weir, author of The Martian.',
    price: 18.99,
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Ballantine Books',
    images: [{ url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794', alt: 'Book' }],
    stock: 250,
    ratings: { average: 4.7, count: 3421 },
  },
  {
    name: 'Educated: A Memoir',
    description: 'A powerful memoir by Tara Westover about self-invention and education.',
    price: 15.99,
    category: 'Books',
    subcategory: 'Biography',
    brand: 'Random House',
    images: [{ url: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090', alt: 'Book' }],
    stock: 320,
    ratings: { average: 4.8, count: 1876 },
  },
  {
    name: 'The Midnight Library',
    description: 'A novel about life, death, and infinite possibilities by Matt Haig.',
    price: 17.49,
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Viking',
    images: [{ url: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e', alt: 'Book' }],
    stock: 280,
    ratings: { average: 4.6, count: 2543 },
  },
  {
    name: 'Sapiens: A Brief History of Humankind',
    description: 'Yuval Noah Harari explores the history and impact of Homo sapiens.',
    price: 19.99,
    category: 'Books',
    subcategory: 'History',
    brand: 'Harper',
    images: [{ url: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6', alt: 'Book' }],
    stock: 390,
    ratings: { average: 4.7, count: 3892 },
  },
  {
    name: 'Becoming',
    description: 'Michelle Obama\'s powerful and inspiring memoir.',
    price: 16.50,
    category: 'Books',
    subcategory: 'Biography',
    brand: 'Crown',
    images: [{ url: 'https://images.unsplash.com/photo-1519682337058-a94d519337bc', alt: 'Book' }],
    stock: 340,
    ratings: { average: 4.9, count: 4234 },
  },
  {
    name: 'Where the Crawdads Sing',
    description: 'A compelling mystery and coming-of-age story by Delia Owens.',
    price: 15.99,
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Putnam',
    images: [{ url: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570', alt: 'Book' }],
    stock: 410,
    ratings: { average: 4.6, count: 5123 },
  },
  {
    name: 'Thinking, Fast and Slow',
    description: 'Nobel Prize winner Daniel Kahneman explores human decision-making.',
    price: 18.99,
    category: 'Books',
    subcategory: 'Psychology',
    brand: 'Farrar, Straus and Giroux',
    images: [{ url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d', alt: 'Book' }],
    stock: 260,
    ratings: { average: 4.5, count: 1987 },
  },
  {
    name: '1984',
    description: 'George Orwell\'s dystopian classic about totalitarianism.',
    price: 12.99,
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'Signet Classic',
    images: [{ url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d', alt: 'Book' }],
    stock: 500,
    ratings: { average: 4.8, count: 6234 },
  },
  {
    name: 'The 7 Habits of Highly Effective People',
    description: 'Stephen Covey\'s classic guide to personal and professional effectiveness.',
    price: 14.99,
    category: 'Books',
    subcategory: 'Self-Help',
    brand: 'Free Press',
    images: [{ url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794', alt: 'Book' }],
    stock: 380,
    ratings: { average: 4.7, count: 3421 },
  },
  {
    name: 'The Alchemist',
    description: 'Paulo Coelho\'s enchanting novel about following your dreams.',
    price: 13.99,
    category: 'Books',
    subcategory: 'Fiction',
    brand: 'HarperOne',
    images: [{ url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c', alt: 'Book' }],
    stock: 450,
    ratings: { average: 4.6, count: 4567 },
  },

  // Home & Kitchen - 15 products
  {
    name: 'Instant Pot Duo 7-in-1',
    description: 'Multi-use pressure cooker, slow cooker, rice cooker, steamer, and more.',
    price: 89.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Instant Pot',
    images: [{ url: 'https://images.unsplash.com/photo-1585515320310-259814833e62', alt: 'Instant Pot' }],
    stock: 120,
    ratings: { average: 4.7, count: 3421 },
    discount: 25,
  },
  {
    name: 'KitchenAid Stand Mixer',
    description: '5-quart tilt-head stand mixer with 10 speeds and multiple attachments.',
    price: 379.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'KitchenAid',
    images: [{ url: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b', alt: 'Mixer' }],
    stock: 80,
    ratings: { average: 4.9, count: 2134 },
  },
  {
    name: 'Dyson V15 Detect Vacuum',
    description: 'Cordless stick vacuum with laser dust detection.',
    price: 699.99,
    category: 'Home & Kitchen',
    subcategory: 'Cleaning',
    brand: 'Dyson',
    images: [{ url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001', alt: 'Vacuum' }],
    stock: 45,
    ratings: { average: 4.8, count: 890 },
  },
  {
    name: 'Ninja Professional Blender',
    description: '1000-watt blender with 72 oz pitcher, perfect for smoothies and frozen drinks.',
    price: 79.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Ninja',
    images: [{ url: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b', alt: 'Blender' }],
    stock: 150,
    ratings: { average: 4.6, count: 2876 },
    discount: 20,
  },
  {
    name: 'Cuisinart Coffee Maker',
    description: '12-cup programmable coffee maker with auto-shutoff and brew strength control.',
    price: 89.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Cuisinart',
    images: [{ url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6', alt: 'Coffee Maker' }],
    stock: 200,
    ratings: { average: 4.5, count: 1654 },
  },
  {
    name: 'All-Clad Stainless Steel Cookware Set',
    description: '10-piece professional cookware set with tri-ply construction.',
    price: 599.99,
    category: 'Home & Kitchen',
    subcategory: 'Cookware',
    brand: 'All-Clad',
    images: [{ url: 'https://images.unsplash.com/photo-1556911220-bff31c812dba', alt: 'Cookware' }],
    stock: 60,
    ratings: { average: 4.9, count: 876 },
  },
  {
    name: 'Pyrex Glass Storage Set',
    description: '18-piece glass food storage container set with locking lids.',
    price: 39.99,
    category: 'Home & Kitchen',
    subcategory: 'Storage',
    brand: 'Pyrex',
    images: [{ url: 'https://images.unsplash.com/photo-1584308972272-9e4e7685e80f', alt: 'Storage' }],
    stock: 300,
    ratings: { average: 4.7, count: 3421 },
  },
  {
    name: 'OXO Good Grips Knife Set',
    description: '15-piece knife block set with high-carbon stainless steel blades.',
    price: 149.99,
    category: 'Home & Kitchen',
    subcategory: 'Cutlery',
    brand: 'OXO',
    images: [{ url: 'https://images.unsplash.com/photo-1593618998160-e34014e67546', alt: 'Knife Set' }],
    stock: 100,
    ratings: { average: 4.6, count: 1234 },
  },
  {
    name: 'Lodge Cast Iron Skillet',
    description: '12-inch pre-seasoned cast iron skillet for stovetop and oven.',
    price: 34.99,
    category: 'Home & Kitchen',
    subcategory: 'Cookware',
    brand: 'Lodge',
    images: [{ url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641', alt: 'Skillet' }],
    stock: 180,
    ratings: { average: 4.8, count: 4567 },
  },
  {
    name: 'Anova Sous Vide Precision Cooker',
    description: 'WiFi-enabled immersion circulator for restaurant-quality cooking.',
    price: 199.00,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Anova',
    images: [{ url: 'https://images.unsplash.com/photo-1556911220-bff31c812dba', alt: 'Sous Vide' }],
    stock: 70,
    ratings: { average: 4.7, count: 987 },
  },
  {
    name: 'Breville Toaster Oven',
    description: 'Smart oven with 13 cooking functions and convection technology.',
    price: 349.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Breville',
    images: [{ url: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd', alt: 'Toaster Oven' }],
    stock: 90,
    ratings: { average: 4.8, count: 1543 },
  },
  {
    name: 'Roomba i7+ Robot Vacuum',
    description: 'Self-emptying robot vacuum with smart mapping and voice control.',
    price: 799.99,
    category: 'Home & Kitchen',
    subcategory: 'Cleaning',
    brand: 'iRobot',
    images: [{ url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64', alt: 'Robot Vacuum' }],
    stock: 55,
    ratings: { average: 4.5, count: 2134 },
    discount: 30,
  },
  {
    name: 'Wüsthof Classic Knife Block',
    description: '7-piece German knife set with high-carbon stainless steel.',
    price: 399.99,
    category: 'Home & Kitchen',
    subcategory: 'Cutlery',
    brand: 'Wüsthof',
    images: [{ url: 'https://images.unsplash.com/photo-1593618998160-e34014e67546', alt: 'Knife Block' }],
    stock: 75,
    ratings: { average: 4.9, count: 654 },
  },
  {
    name: 'Nespresso Vertuo Coffee Machine',
    description: 'Single-serve coffee and espresso maker with barcode scanning.',
    price: 199.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Nespresso',
    images: [{ url: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6', alt: 'Nespresso' }],
    stock: 130,
    ratings: { average: 4.6, count: 2876 },
  },
  {
    name: 'Hamilton Beach Air Fryer',
    description: '6-quart digital air fryer with 8 presets and nonstick basket.',
    price: 69.99,
    category: 'Home & Kitchen',
    subcategory: 'Appliances',
    brand: 'Hamilton Beach',
    images: [{ url: 'https://images.unsplash.com/photo-1585515320310-259814833e62', alt: 'Air Fryer' }],
    stock: 220,
    ratings: { average: 4.4, count: 1987 },
    discount: 15,
  },

  // Sports & Outdoors - 10 products
  {
    name: 'Yoga Mat Premium',
    description: 'Non-slip, eco-friendly yoga mat with carrying strap.',
    price: 34.99,
    category: 'Sports & Outdoors',
    subcategory: 'Fitness',
    brand: 'Manduka',
    images: [{ url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f', alt: 'Yoga Mat' }],
    stock: 300,
    ratings: { average: 4.4, count: 234 },
  },
  {
    name: 'Bowflex Adjustable Dumbbells',
    description: 'Space-saving dumbbells, adjustable from 5 to 52.5 lbs.',
    price: 349.99,
    category: 'Sports & Outdoors',
    subcategory: 'Fitness',
    brand: 'Bowflex',
    images: [{ url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438', alt: 'Dumbbells' }],
    stock: 60,
    ratings: { average: 4.7, count: 567 },
  },
  {
    name: 'Peloton Bike Basics',
    description: 'Indoor cycling bike with adjustable seat and resistance.',
    price: 1445.00,
    category: 'Sports & Outdoors',
    subcategory: 'Fitness',
    brand: 'Peloton',
    images: [{ url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48', alt: 'Exercise Bike' }],
    stock: 25,
    ratings: { average: 4.8, count: 1234 },
    isFeatured: true,
  },
  {
    name: 'Wilson Basketball',
    description: 'Official size and weight basketball with superior grip.',
    price: 29.99,
    category: 'Sports & Outdoors',
    subcategory: 'Team Sports',
    brand: 'Wilson',
    images: [{ url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc', alt: 'Basketball' }],
    stock: 250,
    ratings: { average: 4.6, count: 892 },
  },
  {
    name: 'TaylorMade Golf Club Set',
    description: 'Complete golf set with driver, irons, wedges, and putter.',
    price: 899.99,
    category: 'Sports & Outdoors',
    subcategory: 'Golf',
    brand: 'TaylorMade',
    images: [{ url: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b', alt: 'Golf Clubs' }],
    stock: 40,
    ratings: { average: 4.7, count: 456 },
  },
  {
    name: 'Coleman Camping Tent',
    description: '6-person dome tent with WeatherTec system and easy setup.',
    price: 149.99,
    category: 'Sports & Outdoors',
    subcategory: 'Camping',
    brand: 'Coleman',
    images: [{ url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4', alt: 'Tent' }],
    stock: 80,
    ratings: { average: 4.5, count: 1345 },
    discount: 25,
  },
  {
    name: 'Hydro Flask Water Bottle',
    description: '32 oz insulated stainless steel water bottle keeps drinks cold 24 hours.',
    price: 44.95,
    category: 'Sports & Outdoors',
    subcategory: 'Outdoor Recreation',
    brand: 'Hydro Flask',
    images: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8', alt: 'Water Bottle' }],
    stock: 400,
    ratings: { average: 4.8, count: 2876 },
  },
  {
    name: 'NordicTrack Treadmill',
    description: 'Folding treadmill with iFit compatibility and 10% incline.',
    price: 799.00,
    category: 'Sports & Outdoors',
    subcategory: 'Fitness',
    brand: 'NordicTrack',
    images: [{ url: 'https://images.unsplash.com/photo-1576678927484-cc907957088c', alt: 'Treadmill' }],
    stock: 30,
    ratings: { average: 4.4, count: 678 },
  },
  {
    name: 'Spalding Portable Basketball Hoop',
    description: 'Adjustable height basketball system with 54-inch backboard.',
    price: 399.99,
    category: 'Sports & Outdoors',
    subcategory: 'Team Sports',
    brand: 'Spalding',
    images: [{ url: 'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0', alt: 'Basketball Hoop' }],
    stock: 50,
    ratings: { average: 4.5, count: 543 },
  },
  {
    name: 'Schwinn Mountain Bike',
    description: '29-inch wheels, 21-speed, full suspension mountain bike.',
    price: 549.99,
    category: 'Sports & Outdoors',
    subcategory: 'Cycling',
    brand: 'Schwinn',
    images: [{ url: 'https://images.unsplash.com/photo-1576435728678-68d0fbf94e91', alt: 'Mountain Bike' }],
    stock: 45,
    ratings: { average: 4.3, count: 789 },
  },

  // Toys & Games - 8 products
  {
    name: 'LEGO Star Wars Millennium Falcon',
    description: 'Build and display this iconic starship with 7,541 pieces.',
    price: 849.99,
    category: 'Toys & Games',
    subcategory: 'Building Sets',
    brand: 'LEGO',
    images: [{ url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b', alt: 'LEGO Set' }],
    stock: 15,
    ratings: { average: 5.0, count: 89 },
    isFeatured: true,
  },
  {
    name: 'Nintendo Switch OLED',
    description: 'Gaming console with 7-inch OLED screen and enhanced audio.',
    price: 349.99,
    category: 'Toys & Games',
    subcategory: 'Video Games',
    brand: 'Nintendo',
    images: [{ url: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e', alt: 'Nintendo Switch' }],
    stock: 100,
    ratings: { average: 4.9, count: 3456 },
    isFeatured: true,
  },
  {
    name: 'PlayStation 5 Console',
    description: 'Next-gen gaming console with ultra-high speed SSD and 4K gaming.',
    price: 499.99,
    category: 'Toys & Games',
    subcategory: 'Video Games',
    brand: 'Sony',
    images: [{ url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3', alt: 'PS5' }],
    stock: 50,
    ratings: { average: 4.8, count: 2876 },
    isFeatured: true,
  },
  {
    name: 'Barbie Dreamhouse',
    description: '3-story dollhouse with 10 rooms, pool, slide, and 70+ accessories.',
    price: 199.99,
    category: 'Toys & Games',
    subcategory: 'Dolls',
    brand: 'Mattel',
    images: [{ url: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaeb55', alt: 'Dollhouse' }],
    stock: 75,
    ratings: { average: 4.7, count: 1543 },
  },
  {
    name: 'Nerf Elite Blaster',
    description: 'Motorized dart blaster with 100-dart capacity and rapid fire.',
    price: 49.99,
    category: 'Toys & Games',
    subcategory: 'Outdoor Play',
    brand: 'Nerf',
    images: [{ url: 'https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8', alt: 'Nerf Gun' }],
    stock: 200,
    ratings: { average: 4.6, count: 987 },
    discount: 20,
  },
  {
    name: 'Hot Wheels Track Set',
    description: 'Epic crash and race track with loops, launchers, and 5 cars.',
    price: 79.99,
    category: 'Toys & Games',
    subcategory: 'Vehicles',
    brand: 'Hot Wheels',
    images: [{ url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64', alt: 'Track Set' }],
    stock: 150,
    ratings: { average: 4.5, count: 765 },
  },
  {
    name: 'Monopoly Board Game',
    description: 'Classic real estate trading game for family game night.',
    price: 19.99,
    category: 'Toys & Games',
    subcategory: 'Board Games',
    brand: 'Hasbro',
    images: [{ url: 'https://images.unsplash.com/photo-1632501641765-e568d28b0015', alt: 'Monopoly' }],
    stock: 300,
    ratings: { average: 4.7, count: 2134 },
  },
  {
    name: 'LEGO City Police Station',
    description: 'Build a police headquarters with jail cells, helicopter, and vehicles.',
    price: 99.99,
    category: 'Toys & Games',
    subcategory: 'Building Sets',
    brand: 'LEGO',
    images: [{ url: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b', alt: 'LEGO Police' }],
    stock: 120,
    ratings: { average: 4.8, count: 654 },
  },
];

const sampleUsers = [
  {
    email: 'admin@amazon.com',
    password: 'admin123',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    isVerified: true,
  },
  {
    email: 'john.doe@example.com',
    password: 'password123',
    firstName: 'John',
    lastName: 'Doe',
    role: 'customer',
    isVerified: true,
  },
];

async function seed() {
  try {
    console.log('🌱 Starting database seeding...\n');

    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Connect to PostgreSQL
    await sequelize.authenticate();
    await sequelize.sync({ force: true }); // Warning: This will drop all tables
    console.log('✅ Connected to PostgreSQL\n');

    // Clear existing data
    await Product.deleteMany({});
    console.log('🗑️  Cleared products');

    // Seed products
    console.log('📦 Seeding products...');
    const products = await Product.insertMany(sampleProducts);
    console.log(`✅ Created ${products.length} products\n`);

    // Seed users
    console.log('👥 Seeding users...');
    for (const userData of sampleUsers) {
      await User.create(userData);
    }
    console.log(`✅ Created ${sampleUsers.length} users\n`);

    console.log('🎉 Database seeding completed successfully!');
    console.log('\n📝 Sample credentials:');
    console.log('   Admin: admin@amazon.com / admin123');
    console.log('   User: john.doe@example.com / password123\n');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
}

seed();
